name: Load Supported Versions

on:
  workflow_call:
    outputs:
      matrix:
        description: "Matrix of supported versions"
        value: ${{ jobs.load_versions.outputs.matrix }}

jobs:
  load_versions:
    runs-on: ubuntu-20.04
    outputs:
      azcli_version: ${{ env.azcli_version }}
      tf_version: ${{ env.tf_version }}
      matrix: ${{ env.matrix }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Save supported versions as output
        id: set-matrix
        run: |
          echo -e matrix=\{"azcli_version": $(jq -r -c '.azcli_version | sort | reverse' supported_versions.json), "tf_version": $(jq -r -c '.tf_version | sort | reverse' supported_versions.json)\} >> $GITHUB_ENV

      - name: output
        run: echo $matrix

  display_versions:
    needs: load_versions
    runs-on: ubuntu-latest
    steps:
        - name: Access Variable
          run: echo "matrix=${{ needs.load_versions.outputs.matrix }}"
