name: lint-dockerfile

# trigger on any push
# but not on master or tags
# and only for Dockerfile related modifications
on:
  push:
    tags-ignore:
      - "**"
    branches:
      - "**"
      - "!master"
    paths:
      - "Dockerfile"
      - "hadolint.yaml"
      - ".github/workflows/lint-dockerfile.yml"

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "Dockerfile"
          config: "hadolint.yaml"
