name: Load Supported Versions

on:
  workflow_call:
    outputs:
      get_versions:
        description: "Matrix of supported versions"
        value: ${{ jobs.load_versions.outputs.versions }}
  workflow_dispatch:

jobs:
  load_versions:
    runs-on: ubuntu-20.04

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Get supported versions
        id: set-matrix
        run: |
          SUPPORTED_VERSIONS=$(cat ./supported_versions.json)
          SUPPORTED_VERSIONS="${SUPPORTED_VERSIONS//'%'/%25}"
          SUPPORTED_VERSIONS="${SUPPORTED_VERSIONS//$'\n'/%0A}"
          SUPPORTED_VERSIONS="${SUPPORTED_VERSIONS//$'\r'/%0D}"
          echo "::set-output name=matrix::${SUPPORTED_VERSIONS}"

      - name: Display supported versions
        id: show-versions
        run: echo $steps.set-matrix.outputs.matrix
