name: test_supported-versions.yaml
on:
  push:
jobs:
  load_versions:
    uses: ./.github/workflows/supported-versions.yml

  mainjob2:
    runs-on: ubuntu-latest
    needs: load_versions
    # strategy:
    #   matrix: ${{ fromJSON(needs.load_versions.outputs.matrix) }}

    steps:
      - name: Access Variable
        run: |
          echo ${{ needs.load_versions.outputs.matrix }}
          echo tf_${{ matrix.tf_version }}_azcli-${{ matrix.azcli_version }}
