name: Main Workflow

on:
  push:

jobs:
  mainjob1:
    runs-on: ubuntu-latest
    outputs:
      var1: ${{ steps.set_var.outputs.var1 }}
    steps:
      - name: Set Variable
        id: set_var
        run: |
          echo "var1=good" >> $GITHUB_OUTPUT

  mainjob2:
    needs: mainjob1
    runs-on: ubuntu-latest

    steps:

      - name: Access Variable
        run: |
          echo "var1=${{ needs.mainjob1.outputs.var1 }}"
