name: test-harness
on:
  push:

jobs:
  load_supported_versions:
    uses: ./.github/workflows/supported-versions.yml
  test-harness:
    runs-on: ubuntu-20.04
    needs: load_supported_versions
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Display matrix
        run: |
          echo ${{ needs.load_supported_versions.outputs.get_versions }}
          echo ${{ job.load_supported_versions.outputs.get_versions }}
